# **Hypothesis Testing**


**Cutlets**

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Cutlets.csv to Cutlets.csv


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from scipy import stats

In [ ]:
Cutlets=pd.read_csv('Cutlets.csv')
Cutlets

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [ ]:
Cutlets.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [ ]:
Cutlets['Unit A'].unique()

array([6.809 , 6.4376, 6.9157, 7.3012, 7.4488, 7.3871, 6.8755, 7.0621,
       6.684 , 6.8236, 7.393 , 7.5169, 6.9246, 6.9256, 6.5797, 6.8394,
       6.597 , 7.2705, 7.2828, 7.3495, 6.9438, 7.156 , 6.5341, 7.2854,
       6.9952, 6.8568, 7.2163, 6.6801, 6.9431, 7.0852, 6.7794, 7.2783,
       7.1561, 7.3943, 6.9405])

In [ ]:
UnitA=pd.Series([6.809 , 6.4376, 6.9157, 7.3012, 7.4488, 7.3871, 6.8755, 7.0621,
       6.684 , 6.8236, 7.393 , 7.5169, 6.9246, 6.9256, 6.5797, 6.8394,
       6.597 , 7.2705, 7.2828, 7.3495, 6.9438, 7.156 , 6.5341, 7.2854,
       6.9952, 6.8568, 7.2163, 6.6801, 6.9431, 7.0852, 6.7794, 7.2783,
       7.1561, 7.3943, 6.9405])

In [ ]:
Cutlets['Unit B'].unique()

array([6.7703, 7.5093, 6.73  , 6.7878, 7.1522, 6.811 , 7.2212, 6.6606,
       7.2402, 7.0503, 6.881 , 7.4059, 6.7652, 6.038 , 7.1581, 7.024 ,
       6.6672, 7.4314, 7.307 , 6.7478, 6.8889, 7.422 , 6.5217, 7.1688,
       6.7594, 6.9399, 7.0133, 6.9182, 6.3346, 7.5459, 7.0992, 7.118 ,
       6.6965, 6.578 , 7.3875])

In [ ]:
UnitB=pd.Series([6.7703, 7.5093, 6.73  , 6.7878, 7.1522, 6.811 , 7.2212, 6.6606,
       7.2402, 7.0503, 6.881 , 7.4059, 6.7652, 6.038 , 7.1581, 7.024 ,
       6.6672, 7.4314, 7.307 , 6.7478, 6.8889, 7.422 , 6.5217, 7.1688,
       6.7594, 6.9399, 7.0133, 6.9182, 6.3346, 7.5459, 7.0992, 7.118 ,
       6.6965, 6.578 , 7.3875])

In [ ]:
stats.ttest_ind(UnitA, UnitB)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

--------------------------------------------------------------------------------

**Lab TAT**

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving LabTAT.csv to LabTAT.csv


In [ ]:
df=pd.read_csv('LabTAT.csv')
df

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [ ]:
p_value=stats.f_oneway(df.iloc[:,0],df.iloc[:,1],df.iloc[:,2],df.iloc[:,3])

In [ ]:
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

---------------------------------------------------------------------



**Buyer Ratio**

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving BuyerRatio.csv to BuyerRatio.csv


In [ ]:
df=pd.read_csv('BuyerRatio.csv')
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
df_table=df.iloc[:,1:6]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [ ]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [ ]:
val=stats.chi2_contingency(df_table)
val

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [ ]:
type(val)

scipy.stats.contingency.Chi2ContingencyResult

In [ ]:
no_of_rows=len(df_table.iloc[0:2,0])
no_of_columns=len(df_table.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [ ]:
Expected_value=val[3]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [ ]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [ ]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [ ]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [ ]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [ ]:
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


-----------------------------------------------------------------------------------

**Customer Order Form**

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm.csv


In [ ]:
df=pd.read_csv('Costomer+OrderForm.csv')
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [ ]:
df.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [ ]:
df.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [ ]:
df.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [ ]:
df.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [ ]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [ ]:
chi2_contingency(obs)

Chi2ContingencyResult(statistic=3.858960685820355, pvalue=0.2771020991233135, dof=3, expected_freq=array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]]))

===================================================================================================================